# Data Science base docker-compose file
version: '3.8'

services:
  pgdb:
    container_name: lucky-parking-postgres
    image: postgis/postgis
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - target: 5432
        published: ${DB_PORT}
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./db-backups/lp-db-dev.sql:/docker-entrypoint-initdb.d/lp-db-dev.sql

volumes:
  pgdb:
    driver: local